"""Initial migration

Revision ID: 23312bc3cafa
Revises: 
Create Date: 2025-10-20 15:18:55.109358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23312bc3cafa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditrun',
    sa.Column('RunId', sa.String(), nullable=False),
    sa.Column('TriggerType', sa.String(), nullable=True),
    sa.Column('Scope', sa.JSON(), nullable=True),
    sa.Column('StartTime', sa.DateTime(), nullable=True),
    sa.Column('EndTime', sa.DateTime(), nullable=True),
    sa.Column('Status', sa.String(), nullable=True),
    sa.Column('FindingsCount', sa.Integer(), nullable=True),
    sa.Column('ReportId', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('RunId')
    )
    op.create_table('controlcatalog',
    sa.Column('ControlId', sa.String(), nullable=False),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('Domain', sa.String(), nullable=True),
    sa.Column('BenchmarkMappings', sa.JSON(), nullable=True),
    sa.Column('Evaluator', sa.String(), nullable=True),
    sa.Column('SeverityRules', sa.JSON(), nullable=True),
    sa.Column('Recommendation', sa.Text(), nullable=True),
    sa.Column('RemediationType', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ControlId')
    )
    op.create_table('evidence',
    sa.Column('EvidenceId', sa.String(), nullable=False),
    sa.Column('Source', sa.String(), nullable=True),
    sa.Column('QueryOrRequest', sa.Text(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('RawResult', sa.JSON(), nullable=True),
    sa.Column('Hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('EvidenceId')
    )
    op.create_table('finding',
    sa.Column('FindingId', sa.String(), nullable=False),
    sa.Column('ControlId', sa.String(), nullable=True),
    sa.Column('Domain', sa.String(), nullable=True),
    sa.Column('Severity', sa.Enum('Critical', 'High', 'Medium', 'Low', name='severityenum'), nullable=True),
    sa.Column('RiskScore', sa.Integer(), nullable=True),
    sa.Column('Summary', sa.String(), nullable=True),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('ImpactedResources', sa.JSON(), nullable=True),
    sa.Column('EvidenceRefs', sa.JSON(), nullable=True),
    sa.Column('Recommendation', sa.Text(), nullable=True),
    sa.Column('Remediation', sa.JSON(), nullable=True),
    sa.Column('Status', sa.Enum('Open', 'InProgress', 'Resolved', 'Suppressed', name='findingstatusenum'), nullable=True),
    sa.Column('GeneratedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('FindingId')
    )
    op.create_index(op.f('ix_finding_ControlId'), 'finding', ['ControlId'], unique=False)
    op.create_table('report',
    sa.Column('ReportId', sa.String(), nullable=False),
    sa.Column('Scope', sa.JSON(), nullable=True),
    sa.Column('BenchmarksApplied', sa.JSON(), nullable=True),
    sa.Column('Metrics', sa.JSON(), nullable=True),
    sa.Column('FindingsSnapshot', sa.JSON(), nullable=True),
    sa.Column('GeneratedAt', sa.DateTime(), nullable=True),
    sa.Column('IntegritySignature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ReportId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_index(op.f('ix_finding_ControlId'), table_name='finding')
    op.drop_table('finding')
    op.drop_table('evidence')
    op.drop_table('controlcatalog')
    op.drop_table('auditrun')
    # ### end Alembic commands ###
